### ISSUE TITLE
Dont follow odin ms approach

### ISSUE THREAD

**Issue by dilsonnn** [jonnylin13/omega#26]
Hi. 

You should not try to copy the Odin architecture in your implementation, a much better approach would try to create a architecture like the original based on center / login / game servers using the leaked bms server files. 

The original odin ms approach was good for 2008, but today it would not make sense to follow it. 

A much up to date architecture was MapleGlobal implemented by diamond: 
https://github.com/diamondo25/WvsGlobal

**Comment by jonnylin13** [comment]
Looks good, thanks for sending this. I'll work on it next week when I have time again, looks like a central server that maintains connections to local redis servers?
